# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://ecguo.cloud-mes.com
title: Eric Guo's Blog
subtitle: My playground in HTML5, JavaScript, .NET, Python, Ruby, Google/Sina App Engine and Cloud MES!
author: Eric Guo
simple_search: http://google.com/search
description: My playground in HTML5, JavaScript, .NET, Python, Ruby, Google/Sina App Engine and Cloud MES!

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /Eric-Guo/atom.xml
subscribe_email:
category_feeds: false
# RSS feeds can list your email address if you like
email:
# humans.txt file can list your location if specified
# it also uses 'author', 'email', 'twitter_user' and  'github_user'
location:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /Eric-Guo
permalink: /:year/:month/:day/:title/
source: source
destination: public/Eric-Guo
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
include:
  - .htaccess
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - strikethrough
    - autolink
    - superscript
    - smart

pygments: false # Jekyll's default Python Pygments have been replaced by pygments.rb. Set to true to use Albino + Pythong Pygments

paginate: 12          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 7       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_in_feed: false # Truncate excerpted articles in the atom feed
permalink_label: "Permalink"
permalink_label_feed: "&#9875; Permalink"
linklog_marker: "&rarr;"
linklog_marker_position: after
linklog_marker_position_feed: after
standard_post_marker:

titlecase: true       # Converts page and post titles to titlecase

# To change the layout's default sidebar Add a new sidebar source/_includes/sidebars/your_sidebar.html
# then make changes below, eg. post_sidebar: your_sidebar.html
blog_index_sidebar: blog_index_default.html
page_sidebar: page_default.html
post_sidebar: post_default.html

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Javascript social buttons often generate lots of http requests and may track your viewer's browsing history
# Show respect for privacy and bandwidth with simple links for Twitter, Facebook and Google Plus.
respectfully_social: true

# Github repositories
github_user: Eric-Guo
github_repo_count: 9
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: ecguo
twitter_tweet_count: 4
twitter_widget_id:  # apply widget id from https://twitter.com/settings/widgets/new
twitter_follow_button: true
twitter_show_follower_count: false

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
google_plus_user: 111227458915455234901
google_plus_hidden: false
google_plus_image_size: 32

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false
disqus_developer: 0

# Google Analytics
google_analytics_tracking_id:
google_analytics_set_domain_name:         # Tracking one domain with multiple subdomains
google_analytics_set_allow_linker: false  # Tracking multiple top-level domains

# Gaug.es Analytics
gauges_analytics_tracking_id:

# Facebook Like
facebook_like: false

# Weibo Share Button
weibo_share: true
weibo_uid: ecguo
